Update terraform-stages-template.yml

diff --git a/infrastructure/terraform-stages-template.yml b/infrastructure/terraform-stages-template.yml
--- a/infrastructure/terraform-stages-template.yml
+++ b/infrastructure/terraform-stages-template.yml
@@ -72,7 +72,7 @@ stages:
           export ARM_CLIENT_SECRET="$servicePrincipalKey"
           export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
           export ARM_TENANT_ID="$tenantId"
-          terraform plan -out=tfplan  -var environment=${{ parameters.environment }} ${{ parameters.TerraformVariables }}
+          terraform plan -out=tfplan -var environment=${{ parameters.environment }} ${{ parameters.TerraformVariables }}
         workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/terraform'
         addSpnToEnvironment: true
       displayName: 'Terraform plan'
@@ -127,6 +127,9 @@ stages:
               backendAzureRmContainerName: ${{ parameters.TerraformBackendStorageContainer }}
               backendAzureRmKey: ${{ parameters.environment }}.tfstate
 
+          # As the Terraform extension plan task doesn't support -detailed-exitcode
+          # (to check if any changes are present), we define an equivalent AzureCLI
+          # task instead.
           - task: AzureCLI@1
             inputs:
               azureSubscription: '${{ parameters.TerraformEnvironmentServiceConnection }}'
@@ -137,7 +140,16 @@ stages:
                 export ARM_CLIENT_SECRET="$servicePrincipalKey"
                 export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                 export ARM_TENANT_ID="$tenantId"
-                terraform plan -out=tfplan  -var environment=${{ parameters.environment }} ${{ parameters.TerraformVariables }}
+                # terraform plan -detailed-exitcode exit codes:
+                # 0 - Succeeded, diff is empty (no changes)
+                # 1 - Errored
+                # 2 - Succeeded, there is a diff
+                if ! terraform plan -detailed-exitcode -out=tfplan -var environment=${{ parameters.environment }} ${{ parameters.TerraformVariables }}; then
+                  if [ $? -eq 1 ]; then
+                   exit $?
+                  fi
+                  echo "##vso[task.setvariable variable=TERRAFORM_UPDATES;]true"
+                fi
               workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_resources'
               addSpnToEnvironment: true
             displayName: 'Terraform plan'
@@ -151,6 +163,7 @@ stages:
 
           - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
             displayName: 'Terraform apply'
+            condition: and(succeeded(), variables['TERRAFORM_UPDATES'])
             inputs:
               command: apply
               workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_resources'
