Update terraform-stages-template.yml

diff --git a/infrastructure/terraform-stages-template.yml b/infrastructure/terraform-stages-template.yml
--- a/infrastructure/terraform-stages-template.yml
+++ b/infrastructure/terraform-stages-template.yml
@@ -28,12 +28,12 @@ stages:
         inlineScript: |
           set -eux  # fail on error
           time az configure --defaults group='${{ parameters.TerraformBackendResourceGroup }}' location='${{ parameters.TerraformBackendLocation }}'
-          time az group create -n '${{ parameters.TerraformBackendResourceGroup }}' -o table
-          time az storage account create  -n '${{ parameters.TerraformBackendStorageAccount }}' -o table
-          time az storage container create --account-name '${{ parameters.TerraformBackendStorageAccount }}' -n '${{ parameters.TerraformBackendStorageContainer }}' -o table
-          time az keyvault create -n '${{ parameters.TerraformBackendKeyVault }}' -o table
-          time az keyvault secret set --vault-name '${{ parameters.TerraformBackendKeyVault }}' -n "${{ parameters.environment }}-sql-password" --value "Str0ng!Passw0wrd" -o table
-          time az keyvault set-policy -n '${{ parameters.TerraformBackendKeyVault }}' --spn "$servicePrincipalId" --secret-permissions get list -o table
+          time az group create -n '${{ parameters.TerraformBackendResourceGroup }}' -o none
+          time az storage account create  -n '${{ parameters.TerraformBackendStorageAccount }}' -o none
+          time az storage container create --account-name '${{ parameters.TerraformBackendStorageAccount }}' -n '${{ parameters.TerraformBackendStorageContainer }}' -o none
+          time az keyvault create -n '${{ parameters.TerraformBackendKeyVault }}' -o none
+          time az keyvault secret set --vault-name '${{ parameters.TerraformBackendKeyVault }}' -n "${{ parameters.environment }}-sql-password" --value "Str0ng!Passw0wrd" -o none
+          time az keyvault set-policy -n '${{ parameters.TerraformBackendKeyVault }}' --spn "$servicePrincipalId" --secret-permissions get list -o none
         addSpnToEnvironment: true
       displayName: 'Set up backend and Key Vault'
 
@@ -70,6 +70,10 @@ stages:
     # Resource providers can be > 100MB large, we don't want them in the published artifacts.
     - bash: |
         set -eux
+        if ! test -f $(terraform_plan.jsonPlanFilePath); then
+          echo "Terraform plan failed."
+          exit 1
+        fi
         terraform show -no-color tfplan > plan.txt
         rm -r tfplan .terraform
       workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/terraform'
