Update terraform-stages-template.yml

diff --git a/infrastructure/terraform-stages-template.yml b/infrastructure/terraform-stages-template.yml
--- a/infrastructure/terraform-stages-template.yml
+++ b/infrastructure/terraform-stages-template.yml
@@ -67,18 +67,35 @@ stages:
         environmentServiceNameAzureRM: '${{ parameters.TerraformEnvironmentServiceConnection }}'
         backendServiceArm: '${{ parameters.TerraformBackendServiceConnection }}'
 
-    # Resource providers can be > 100MB large, we don't want them in the published artifacts.
-    - bash: |
-        set -eux
-        # Workaround for https://github.com/microsoft/azure-pipelines-extensions/issues/747
-        if ! test -s $(terraform_plan.jsonPlanFilePath); then
-          echo "Terraform plan failed."
-          exit 1
-        fi
-        terraform show -no-color tfplan > plan.txt
-        rm -r tfplan .terraform
-      workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/terraform'
-      displayName: 'Check plan and delete derived terraform resources'
+    # Workaround for https://github.com/microsoft/azure-pipelines-extensions/issues/747
+    - task: AzureCLI@1
+      inputs:
+        azureSubscription: '${{ parameters.TerraformEnvironmentServiceConnection }}'
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -eu
+          export ARM_CLIENT_ID="$servicePrincipalId"
+          export ARM_CLIENT_SECRET="$servicePrincipalKey"
+          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          export ARM_TENANT_ID="$tenantId"
+          # terraform plan -detailed-exitcode exit codes:
+          # 0 - Succeeded, diff is empty (no changes)
+          # 1 - Errored
+          # 2 - Succeeded, there is a diff
+          if ! terraform plan -detailed-exitcode -out=tfplan  -var environment=${{ parameters.environment }} ${{ parameters.TerraformVariables }}; then
+           if [ $? -eq 1 ]; then
+            exit $?
+           fi
+          fi
+          # Resource providers can be > 100MB large, we don't want them in the published artifacts.
+          terraform show -no-color tfplan > plan.txt
+          # Remove terraform plan from published artifacts, as it contains clear-text secrets
+          rm tfplan
+          # Resource providers can be > 100MB large, we don't want them in the published artifacts.
+          rm -r .terraform
+        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/terraform'
+        addSpnToEnvironment: true
+      displayName: 'Terraform plan'
 
     - task: PublishPipelineArtifact@1
       displayName: 'Publish Pipeline Artifact'
