Using bash instead of Terraform extension for terraform init (#7)

diff --git a/infrastructure/terraform-init-template.yml b/infrastructure/terraform-init-template.yml
--- a/infrastructure/terraform-init-template.yml
+++ b/infrastructure/terraform-init-template.yml
@@ -58,16 +58,6 @@ steps:
   inputs:
     terraformVersion: ${{ parameters.TerraformVersion }}
 
-- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
-  displayName: Terraform init
-  inputs:
-    workingDirectory: ${{ parameters.TerraformDirectory }}
-    backendServiceArm: ${{ parameters.TerraformBackendServiceConnection }}
-    backendAzureRmResourceGroupName: ${{ parameters.TerraformBackendResourceGroup }}
-    backendAzureRmStorageAccountName: ${{ parameters.TerraformBackendStorageAccount }}
-    backendAzureRmContainerName: ${{ parameters.TerraformBackendStorageContainer }}
-    backendAzureRmKey: ${{ parameters.environment }}.tfstate
-
 - task: AzureCLI@1
   displayName: Terraform credentials
   inputs:
@@ -80,4 +70,26 @@ steps:
       echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
       echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
       echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+    addSpnToEnvironment: true
+
+# Using bash instead of Terraform extension because of following issue:
+# - https://github.com/microsoft/azure-pipelines-extensions/issues/738
+- task: AzureCLI@1
+  displayName: Terraform init
+  inputs:
+    azureSubscription: ${{ parameters.TerraformBackendServiceConnection }}
+    scriptLocation: inlineScript
+    inlineScript: |
+      set -eux  # fail on error
+      subscriptionId=$(az account show --query id -o tsv)
+      terraform init \
+        -backend-config=storage_account_name=${{ parameters.TerraformBackendStorageAccount }} \
+        -backend-config=container_name=${{ parameters.TerraformBackendStorageContainer }} \
+        -backend-config=key=${{ parameters.environment }}.tfstate \
+        -backend-config=resource_group_name=${{ parameters.TerraformBackendResourceGroup }} \
+        -backend-config=subscription_id=$subscriptionId \
+        -backend-config=tenant_id=$tenantId \
+        -backend-config=client_id=$servicePrincipalId \
+        -backend-config=client_secret="$servicePrincipalKey"
+    workingDirectory: ${{ parameters.TerraformDirectory }}
     addSpnToEnvironment: true
